apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  url: https://argoproj.github.io/argo-helm
  interval: 10m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: argo-cd
      version: 5.51.6
      sourceRef:
        kind: HelmRepository
        name: argo-cd
        namespace: flux-system
  values:
    server:
      service:
        type: LoadBalancer
