apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stefanprodan/podinfo
    targetRevision: HEAD
    path: charts/podinfo
    helm:
      values: |
        replicaCount: 2
        service:
          type: LoadBalancer
          port: 80
        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

